### ISSUE TITLE
SetDamageFilter 修改伤害之后，显示的伤害数值怎么改

### ISSUE THREAD

**Issue by cao13646** [RobinCodeX/dota2-coding-helper#21]
SetDamageFilter 修改伤害成功了，实际收到的伤害是修改之后的，但是显示的伤害还是修改之前的。显示的伤害数值怎么改？

**Comment by robincodex** [comment]
只能自定义显示，没有办法修改
另外这里不是提问如何做的地方，请到AMHC群里讨论
