### ISSUE TITLE
command 'dota2CodingHelper.luaClientAPI' not found

### ISSUE THREAD

**Issue by pvp-by** [RobinCodeX/dota2-coding-helper#8]
Hi , im install ext and he not work 
you can help ?
![Screenshot_1](https://user-images.githubusercontent.com/10133995/85916263-182a0680-b860-11ea-8a47-a91ae74981f1.png)

**Comment by robincodex** [comment]
Sorry, I don't know what caused this. You can try to install it again

**Comment by pvp-by** [comment]
i fix , my friend find error , we have ru locale... file not found and ext not work.
i copy and rename file "en.json" > "ru.json"

**Comment by robincodex** [comment]
> i fix , my friend find error , we have ru locale... file not found and ext not work.
> i copy and rename file "en.json" > "ru.json"

OK，thank you, I will fix it later.
